### ISSUE TITLE
F-droid build failed

### ISSUE THREAD

**Issue by linsui** [invoiceninja/admin-portal#314]
```
Execution failed for task ':app:processReleaseResources'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

   > Android resource linking failed

     /home/vagrant/build/com.invoiceninja.app/android/app/src/main/AndroidManifest.xml:13:5-47:19: AAPT: error: resource mipmap/launcher_icon (aka com.invoiceninja.app:mipmap/launcher_icon) not found.
```

Could you please take a look? Thanks!

**Comment by hillelcoren** [comment]
We recently changed the Flutter version to 2.2.3, if the version is hardcoded it could explain the problem.

**Comment by linsui** [comment]
I tried but got https://gitlab.com/linsui/fdroiddata/-/jobs/1500790120.

**Comment by hillelcoren** [comment]
I've tagged a new release (v5.0.58) which may help

**Comment by linsui** [comment]
Thanks! I'll test.

**Comment by linsui** [comment]
I got the same error. The recipe is

```
  - versionName: 5.0.58
    versionCode: 58
    commit: v5.0.58
    output: build/app/outputs/flutter-apk/app-release.apk
    srclibs:
      - flutter@2.2.3
    rm:
      - ios
      - linux
      - macos
      - web
      - windows
    prebuild:
      - cp lib/.env.dart.example lib/.env.dart
      - cp android/app/build.gradle.dev android/app/build.gradle
      - cp android/build.gradle.foss android/build.gradle
      - cp lib/utils/oauth.dart.foss lib/utils/oauth.dart
      - cp lib/ui/app/upgrade_dialog.dart.foss lib/ui/app/upgrade_dialog.dart
      - cp android/app/src/main/AndroidManifest.foss.xml android/app/src/main/AndroidManifest.xml
      - cp pubspec.foss.yaml pubspec.yaml
      - rm pubspec.lock
    build:
      - $$flutter$$/bin/flutter config --no-analytics
      - $$flutter$$/bin/flutter build apk
    ndk: r20
```
