### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [invoiceninja/admin-portal#601]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5350265884#L2127

But we have 3.7.6 as https://github.com/invoiceninja/admin-portal/blob/v5.0.127/.github/workflows/build.yml#L25 says, right?

Yet maybe the issue is that here it says something https://github.com/invoiceninja/admin-portal/blob/v5.0.127/pubspec.yaml#L9

and here it was not updated? https://github.com/invoiceninja/admin-portal/blob/v5.0.127/pubspec.foss.yaml#L9

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/d04c9a1b54e3cf899409bdf9b9edca9822d7049d

**Comment by hillelcoren** [comment]
These changes have been made, let me know if you still have problems building.

**Comment by licaon-kter** [comment]
testing now, brb

**Comment by licaon-kter** [comment]
```
==== detail begin ====
/etc/bash.bashrc: line 7: PS1: unbound variable
++ pwd
+ export PUB_CACHE=/home/vagrant/build/com.invoiceninja.app/.pub-cache
+ PUB_CACHE=/home/vagrant/build/com.invoiceninja.app/.pub-cache
+ /home/vagrant/build/srclib/flutter/bin/flutter build apk
Downloading android-arm-profile/linux-x64 tools...               1,548ms
Downloading android-arm-release/linux-x64 tools...               1,039ms
Downloading android-arm64-profile/linux-x64 tools...             1,185ms
Downloading android-arm64-release/linux-x64 tools...             1,017ms
Downloading android-x64-profile/linux-x64 tools...               1,009ms
Downloading android-x64-release/linux-x64 tools...                 952ms

Upgrading build.gradle
Running Gradle task 'assembleRelease'...                        
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.9.10/dafaf2c27f27c09220cee312df10917d9a5d97ce/kotlin-stdlib-common-1.9.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (32, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (34, 25): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (34, 49): Unresolved reference: listOf
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (37, 25): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (37, 49): Unresolved reference: listOf
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (40, 25): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (44, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (55, 22): Unresolved reference: mutableListOf
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (56, 21): Unresolved reference: until
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (57, 47): Unresolved reference: let
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (58, 28): Unresolved reference: it
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (61, 20): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (63, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (67, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (68, 18): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (72, 16): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (76, 18): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (85, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (86, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (87, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (97, 19): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class
e: /home/vagrant/build/com.invoiceninja.app/.pub-cache/hosted/pub.dev/desktop_drop-0.4.4/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt: (98, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /home/vagrant/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/kotlin/Unit.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':desktop_drop:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10m 31s
Running Gradle task 'assembleRelease'...                          633.0s

┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                     │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then │
│ update /home/vagrant/build/com.invoiceninja.app/android/build.gradle:                      │
│ ext.kotlin_version = '<latest-version>'                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────┘
Gradle task assembleRelease failed with exit code 1
```

with this recipe:
```
  - versionName: 5.0.127
    versionCode: 127
    commit: 6388977ce7b00bdfac9b1e2ca56151bf2dd4d9e2
    output: build/app/outputs/flutter-apk/app-release.apk
    srclibs:
      - flutter@stable
    rm:
      - ios
      - linux
      - macos
      - samples
      - snap
      - test_driver
      - web
      - windows
    prebuild:
      - export version=$(grep "flutter\:\ " codemagic.yaml | tr -d ' ' | cut -d ":"
        -f2)
      - pushd $$flutter$$
      - git checkout -f $version
      - popd
      - cp lib/.env.dart.example lib/.env.dart
      - cp android/app/build.gradle.dev android/app/build.gradle
      - cp android/build.gradle.foss android/build.gradle
      - cp lib/utils/app_review.dart.foss lib/utils/app_review.dart
      - cp lib/utils/oauth.dart.foss lib/utils/oauth.dart
      - cp lib/ui/app/pinput.dart.foss lib/ui/app/pinput.dart
      - cp lib/ui/app/upgrade_dialog.dart.foss lib/ui/app/upgrade_dialog.dart
      - cp android/app/src/main/AndroidManifest.foss.xml android/app/src/main/AndroidManifest.xml
      - cp pubspec.foss.yaml pubspec.yaml
      - sed -i -e '/google_sign_in/d' -e '/in_app_review/d' -e '/in_app_purchase/d'
        pubspec.yaml
      - sed -i -e '/^  google_sign_in/,/version:/d' -e '/^  in_app_review/,/version:/d'
        -e '/^  in_app_purchase/,/version:/d' pubspec.lock
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter config --no-analytics
      - $$flutter$$/bin/flutter pub get
    scandelete:
      - .pub-cache
    build:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter build apk
    ndk: r20
```

@hillelcoren what am I missing?
